# Build configuration
TEMP_DIR="build_tmp"

using_compiler_compile_to() {
	./"$1" "$2".stala -out "$3".asm
	nasm -f macho64 "$3".asm
	ld -macosx_version_min 11.0 -L /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -lSystem -o "$3" "$3".o
	chmod +x "$3"
}